config/routes.rb
Odot::Application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

  

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      user.generate_password_reset_token!
      Notifier.password_reset(user).deliver
      flash[:success] = "Password reset instructions sent! Please check your email."
      redirect_to login_path
    else
      flash.now[:notice] = "Email not found."
      render action: 'new'
    end
  end

  def edit
    @user = User.find_by(password_reset_token: params[:id])
    if @user

    else
      render file: 'public/404.html', status: :not_found
    end
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])
    if @user && @user.update_attributes(user_params)
      @user.update_attribute(:password_reset_token, nil)
      session[:user_id] = @user.id
      redirect_to todo_lists_path, success: "Password updated."
    else
      flash.now[:notice] = "Password reset token not found."
      render action: 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Change Your Password</h1>
<%= form_for @user, url: password_reset_path(@user.password_reset_token), html: { method: :patch } do |form| %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <br />

  <%= form.label :password_confirmation, "Password (again)" %>
  <%= form.password_field :password_confirmation %>

  <br />

  <%= submit_tag "Change Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Your Password</h1>
<%= form_tag password_resets_path do %>
  <%= label_tag :email, "Email" %>
  <%= text_field_tag :email %>

  <br />
  <%= submit_tag "Reset Password" %>
<% end %>